version: "3.9"

services:
  redis:
    image: redis:latest
    container_name: redis
    restart: no
    ports:
      - "6380:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  fastapi-app:
    image: dhiraj918106/phishing_detector_redisapi:latest
    container_name: fastapi-app
    restart: no
    depends_on:
      redis:
        condition: service_healthy
    ports:
      - "8000:8000"
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
