version: "3.9"

services:
  app:
    build: .
    container_name: phishing-app
    ports:
      - "8000:8000"
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379

  redis:
    image: redis:latest
    container_name: redis-server
    ports:
      - "6380:6379"
